### ISSUE TITLE
How to handle the renaming of a project specific modules?

### ISSUE THREAD

**Issue by jcdrubay** [jcdrubay/OpenUpgrade#3]
How to avoid changing the code in the OpenUpgrade repo to do this:

![image](https://user-images.githubusercontent.com/1765420/167747885-ed3ed30e-b565-4042-97f9-f97f79e40d11.png)

**Comment by jcdrubay** [comment]
This should work

![image](https://user-images.githubusercontent.com/1765420/167748156-7a2efb80-9780-4900-8ec8-ff5ce7a6ae97.png)

**Comment by jcdrubay** [comment]
This should probably be documented in 
https://oca.github.io/OpenUpgrade/devfaq.html

@legalsylvain what do you think about it?

**Comment by legalsylvain** [comment]
Hi @jcdrubay. Thanks for the question. I faced the same question several times in the past. Each time I solved with a custom branch of openupgrade with a commit adding custom GRAP changes. Not the better, but it works.

If we want to allow the possibility to add custom rename / merge it should not be done in a pre-migration script of a custom module in my opinion. Two reasons : 
- the apriori.py is used both time. Once in ``openupgrade_framework``, once in ``upgrade_analysis``. If custom values are set in a custom modules, analysis will be wrong.
- in the openupgrade process the rename_modules / merge_modules is used at the very beginning of the upgrade (in the pre-migration.py script of the base module). AFAIK, at the end of the upgrade of base, the modules tree is recompputed (=order of the modules to update). If your custom modules is not renamed at this step, openupgrade will ignore it because it will not find the ``komit_base`` module in your addons path.

So for me, the single solution I see is to add in the ``apriori.py`` file, something like : 

```
_rename_modules = {
    # Odoo
    "crm_iap_lead": "crm_iap_mine",
    # ....
}

def _get_custom_rename_modules():
    # read the odoo.cfg file and search for a openupgrade_rename_modules section
    custom_conf = odoo.tools.config.misc.get('openupgrade_rename_modules', {})    
    return {x:y for x,y in custom_conf.items()}

rename_modules = _rename_modules + _get_custom_rename_modules()
```

And in the ``odoo.cfg`` modules 

```
[openupgrade_rename_modules]
audit_base=k3_audit_base
...
[openupgrade_merged_modules]
```

What do you think ?

**Comment by legalsylvain** [comment]
By the way, you opened an issue on your custom repo, not on https://github.com/OCA/Openupgrade so nobody else can participate could you move your issue ?

**Comment by jcdrubay** [comment]
Thanks for your answer.
I have created the issue in OpenUpgrade repo. ;)
